#!/usr/bin/env python3
"""
Post-process data generated by the code modifier.

This script creates a new folder descriptive_post containing only
files that exist in all three folders (qa_pairs, codes, images) with 1:1 correspondence.

Filtering criteria:
1. qa_pairs: non-failed files (files not starting with "failed_")
2. codes: .py files
3. images: .png files

Only basenames that exist in all three folders are copied.
"""

import argparse
import shutil
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description="Post-process data generated by the code modifier")
    parser.add_argument(
        "--base-dir",
        type=str,
        default="data/ECD/syn_data",
        help="Base directory containing the generated data"
    )
    parser.add_argument(
        "--split-type",
        type=str,
        default="descriptive",
        help="Split type to process (e.g., descriptive, reasoning)"
    )
    args = parser.parse_args()
    base_dir = Path(args.base_dir)
    src_dir = base_dir / args.split_type
    dst_dir = base_dir / f"{args.split_type}_post"

    # Source subdirectories
    src_qa_pairs = src_dir / "qa_pairs"
    src_codes = src_dir / "codes"
    src_images = src_dir / "images"

    # Destination subdirectories
    dst_qa_pairs = dst_dir / "qa_pairs"
    dst_codes = dst_dir / "codes"
    dst_images = dst_dir / "images"

    # Create destination directories
    print(f"Creating destination directory: {dst_dir}")
    dst_dir.mkdir(parents=True, exist_ok=True)
    dst_qa_pairs.mkdir(exist_ok=True)
    dst_codes.mkdir(exist_ok=True)
    dst_images.mkdir(exist_ok=True)

    # Step 1: Get basenames from each folder
    print("\nScanning qa_pairs for non-failed files...")
    qa_basenames = {f.stem for f in src_qa_pairs.iterdir()
                    if f.is_file() and f.suffix == ".json" and not f.name.startswith("failed_")}
    print(f"Found {len(qa_basenames)} non-failed qa_pairs files")

    print("\nScanning codes...")
    codes_basenames = {f.stem for f in src_codes.iterdir()
                       if f.is_file() and f.suffix == ".py"}
    print(f"Found {len(codes_basenames)} codes files")

    print("\nScanning images...")
    images_basenames = {f.stem for f in src_images.iterdir()
                        if f.is_file() and f.suffix == ".png"}
    print(f"Found {len(images_basenames)} images files")

    # Step 2: Get intersection of all three
    valid_basenames = qa_basenames & codes_basenames & images_basenames
    print(f"\nIntersection: {len(valid_basenames)} files have all three (qa_pairs, codes, images)")

    # Step 3: Copy files from all three folders
    print("\nCopying qa_pairs...")
    for basename in valid_basenames:
        shutil.copy2(src_qa_pairs / f"{basename}.json", dst_qa_pairs / f"{basename}.json")
    print(f"Copied {len(valid_basenames)} qa_pairs files")

    print("\nCopying codes...")
    for basename in valid_basenames:
        shutil.copy2(src_codes / f"{basename}.py", dst_codes / f"{basename}.py")
    print(f"Copied {len(valid_basenames)} codes files")

    print("\nCopying images...")
    for basename in valid_basenames:
        shutil.copy2(src_images / f"{basename}.png", dst_images / f"{basename}.png")
    print(f"Copied {len(valid_basenames)} images files")

    # Summary
    print("\n" + "=" * 50)
    print("Summary:")
    print("=" * 50)
    print(f"Destination: {dst_dir}")
    print(f"qa_pairs: {len(valid_basenames)} files")
    print(f"codes: {len(valid_basenames)} files")
    print(f"images: {len(valid_basenames)} files")
    print("=" * 50)


if __name__ == "__main__":
    main()
